### ISSUE TITLE
Block temp/fake email domains

### ISSUE THREAD

**Issue by ymnltd** [Trumani/stop-spammers#105]
The module can fetch the content of the TXT document everyday from the repo mentioned below.
Then we can avoid users to use temp/fake emails.

https://github.com/yzyjim/disposable-email-domain-list 
There are lots of more resources like this in github.

BTW,  I think we can add them manually here
https://prnt.sc/p29reo
but it will be quite hard to compare the list day by day.

**Comment by bhadaway** [comment]
Actually, this feature already exists under:

_Stop Spammers > Protection Options > Deny Disposable Email Addresses_

And should be enabled by default.

That said, absolutely, the current list is out-dated, and could be much more comprehensive.

Thank you and noted for a future update.

**Comment by bhadaway** [comment]
Done! I've just added over 2,500 new disposable email domains to the list. This will be in the next update (2020.4), which is coming soon.
