### ISSUE TITLE
Spam reason empty

### ISSUE THREAD

**Issue by Kipperlenny** [Trumani/stop-spammers#112]
> Webmaster, A request has been received from someone who has been marked as a spammer by the Stop Spammers plugin. You are being notified because you have checked off the box on the settings page indicating that you wanted this email. The information from the request is: ....... Spam Reason: User Message: ..........

Our "Spam Reason" is always empty in the email - why?

**Comment by bhadaway** [comment]
Thanks for reporting this.

Unfortunately, this problem has been present even before I adopted this plugin and is one of many issues that needs to be fixed.

**Comment by bhadaway** [comment]
Fixed.
