### ISSUE TITLE
Translation-ready

### ISSUE THREAD

**Issue by bhadaway** [Trumani/stop-spammers#14]
The biggest update that I'm planning is to make Stop Spammers translation-ready so that it can be translated into other languages besides English.

**Comment by jetsam729** [comment]
for translate must _define name text domain_ - example in my fork
```
define(SFS_TXTDOMAIN,	'sfs-plugin');	// define for translate - if who changed/conflict
$sfs_load_lang = load_plugin_textdomain( SFS_TXTDOMAIN, false, dirname(plugin_basename(__FILE__)) . '/languages');
```
and use as (example add to menu in my fork)
```
	add_submenu_page(
		'stop_spammers', // plugins parent
		__('Summary — Stop Spammers',SFS_TXTDOMAIN), // $page_title,
		__('Summary',SFS_TXTDOMAIN), // $menu_title,
		'manage_options', // $capability,
		'stop_spammers', // $menu_slug,
		'ss_summary' // $function
	);
```
small remark: the names must be the same: at settings pages (example) page **title** "Block Lists — Stop Spammers" but page _header_     `<h1>Stop Spammers — Block Lists</h1>` :) 
It should be the same for beauty and reduction in translation:
or all of "Stop Spammers — _some text_"
or all of _"some text_ — Stop Spammers"
***
I began to translate in my fork into Russian only settings pages now, but We need to agree who will lead\create  the main file (.POT) otherwise it will be double the work

**Comment by bhadaway** [comment]
Yup yup. I've made several themes translation-ready in the past, and it'll mostly be the same here, with a few minor differences.

But ultimately, I know how to do it and need to do it myself because it's going to be fairly tedious, and require checking through a lot of strings in multiple files.

It's just a matter of hunkering down and doing it one day, but that day won't be today. :(

**Comment by jetsam729** [comment]
I completely translated RU and edited POT (я полностью перевел и отредактировал):
```
settings.php
ss_allowlist_settings.php
ss_denylist_settings.php
```
and I can put in /languages/  - i named via
```
define('SFS_TXTDOMAIN',	'sfs-plugin');
$sfs_load_lang = load_plugin_textdomain( SFS_TXTDOMAIN, false, dirname(plugin_basename(__FILE__)) . '/languages');
```
sfs-plugin.pot // base templ 
sfs-plugin-ru_RU.po
sfs-plugin-ru_RU.mo
```
so that everyone can start working on translations.

**Comment by jetsam729** [comment]
https://github.com/jetsam729/stop-spammers-trans
i translated all of  settings/*.php

later i translate modules/*.php (small work)
& later trans *.js

**Comment by bhadaway** [comment]
Awesome. Working on this now.

I might go with a different text domain, so that should be a simple find and replace for your translation.

However, I'm going to give the entire plugin a once over right now, which will likely involve removing entire sections of copy (there's way too much text in some places) and changing some others, so those bits would have to be re-translated. Sorry!

**Comment by jetsam729** [comment]
this is normal. it was an option. _just an option._
I completed the translation. and while it will be available in github.
I’m switching to my light branch - my working version is too different from the master (I removed a lot, which I do not consider useful). I have several separate plugins and I will combine them into one (in one place).

the last refinement - I’ll probably post an addition - determination by countries and asn through geoip (free maxmind lite vers) for filtering without arrays ip :)

by the way, maxmind now has two countries for ip — the country of registration (owner) and the country of the operator (ex hosting) - which often does not coincide together :)

**Comment by bhadaway** [comment]
Okay, I did some code cleanup and implemented the translation structure I would like to use, keeping in line with wporg guidelines. However, I'm not 100% certain it's set up correctly. I wasn't able to get it to work in my test.

If it'll only work if the text domain matches the plugin slug exactly, that'll kind of suck, because that means I'll have to use:

_stop-spammer-registrations-plugin_

Which is just way too long. When I took over the plugin, I asked the admins about shortening it, but the policy is that once the slug is set, it can't ever be changed.

**Comment by jetsam729** [comment]
> If it'll only work if the text domain matches the plugin slug exactly, that'll kind of suck, because that means I'll have to 


no. texdomain loaded as
`load_plugin_textdomain( any_TXTDOMAIN_text_define, false, dirname(plugin_basename(__FILE__)) . langdir);`
_any_TXTDOMAIN_text_define_ maybe **any** name (via define(some_TXTDOMAIN_define,....))
ex: __('some text', any_TXTDOMAIN_define) and lang files as any_TXTDOMAIN_define-locals.po/.mo

I changed the text domain slug several times on the fly - the main thing is to rename the translation files to the text domain

**Comment by bhadaway** [comment]
Yeah, looks like it's just a guideline, but not enforced at the code level.

Alright, so I made some progress, but the translated strings show up blank for some reason.

Here's everything I've added:

In https://github.com/bhadaway/stop-spammers/blob/master/stop-spammer-registrations-new.php:

```
Domain Path: /languages
Text Domain: stop-spammers
```

and

```
// making translation-ready
function ss_load_plugin_textdomain() {
    load_plugin_textdomain( 'stop-spammers', FALSE, basename( dirname( __FILE__ ) ) . '/languages/' );
}

add_action( 'plugins_loaded', 'ss_load_plugin_textdomain' );
```

And then here are the translation files:

https://github.com/bhadaway/stop-spammers/tree/master/languages

**Comment by jetsam729** [comment]
>  load_plugin_textdomain( 'stop-spammers', 

1 not good idea write name textdomain direct. if rename in future - at all files renamed all _(...   :) better - write define - if chg slug  - chg one string with def.
2 for test - `load_plugin_textdomain(`  - not in act\filter - _direct after begin file_ (top).

**Comment by bhadaway** [comment]
1. I agree that it might be easier, but I try to adhere to the standards and guidelines set by WordPress as much as possible, and they recommend not doing that:

https://developer.wordpress.org/themes/functionality/internationalization/

2. Tried it; no difference.

**Comment by jetsam729** [comment]
they not recom via $variable - !not defined!

**Comment by bhadaway** [comment]
That's just an example. The point is they want the text domain explicitly declared for every string. This is how most themes and plugins do it, it's how I've always done it, so I'll stick with it.

But, the major concern here of course is getting the actual translations to work. I'll fuss with it more later. :(

**Comment by bhadaway** [comment]
Done. All strings are now translation-ready and will be in the next update.
