### ISSUE TITLE
Stop all subdomains registrations

### ISSUE THREAD

**Issue by eurobank** [Trumani/stop-spammers#143]
For the last month we have around 100-200 fake new registrations from SUBdomains of compromised sites.

Is there a way to block email that is using a subdomain for registations?

**Comment by bhadaway** [comment]
Are you referring to the new spammers that have been popping up recently with emails like:

janedoe63728@cool**.**sunnyday.travel

I've seen these recently too. I would need to add a new type of blocking to the blocking features.

In the meantime, would you like to try and deal with the spam problem you have now? The more details you can provide, the better. If you need to share info privately, or would like some hands-on assistance, please see:

https://stopspammers.io/pro

Thanks

**Comment by eurobank** [comment]
Yeap exactly. I have been hit hard with those for the last 2 months.

A simple regex could block them i think but how to put that and where. No easy way.

**Comment by bhadaway** [comment]
It's definitely a good pattern to block, and that feature should definitely be added at some point, but I'm sure there are many other ways to harden your WordPress install and block this junk.

Are you currently using the default WordPress login/register forms, or are you using a custom plugin. Adding a CAPTCHA to these forms would be a good step.

**Comment by bhadaway** [comment]
This feature has now been added.
