### ISSUE TITLE
Your server address is 127.0.0.1

### ISSUE THREAD

**Issue by quantumleap33** [Trumani/stop-spammers#144]
On the summary page I see a message "This address is invalid for testing for the following reason: Accessing Site Through localhost."

On the diagnostic page, I receive the message " (Your server address is 127.0.0.1)". As a result, I don't get the user's proper IP. Wordfence properly detects ID as per settings. I am hosted on Cloudways using NGINX and I don't have Varnish enabled so I am not sure what's wrong! I am also not able to report spam to SFS since it throws an error "could not validate api key".

**Comment by bhadaway** [comment]
Please see: https://github.com/Trumani/stop-spammers/issues/36

**Comment by stodorovic** [comment]
If you are using Apache behind NGINX then I recommend to you install module [mod_remoteip](https://httpd.apache.org/docs/current/mod/mod_remoteip.html). 

If it isn't possible then you could set proper IP address in `wp-config.php`. On this way, all plugins will get correct address. Something like this (before the line `/* That's all, stop editing! Happy blogging. */`) :
```php
// Proxy detection.
$trusted_proxies = array( '127.0.0.1', '111.222.233.244', '111.222.233.245' );

if ( ! empty( $_SERVER['REMOTE_ADDR'] ) && in_array( $_SERVER['REMOTE_ADDR'], $trusted_proxies ) ) {
	if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
		$ip_addr = explode( ',', $_SERVER['HTTP_X_FORWARDED_FOR'] );
		$_SERVER['REMOTE_ADDR'] = trim( reset( $ip_addr ) );
		unset( $ip_addr );
	}
	
	if ( $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
		$_SERVER['HTTPS'] = 'on';
	}
}
unset( $trusted_proxies );
```
The array _$trusted_proxies_ should contain list of "trusted proxies". In your case, it's probably only **127.0.0.1**.

**Comment by quantumleap33** [comment]
@stodorovic 

Thank you, Cloudways gave me this code to add to` wp-config.php`, seems to be working:

```
# Use X-Forwarded-For HTTP Header to Get Visitor's Real IP Address
if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
    $http_x_headers = explode( ',', $_SERVER['HTTP_X_FORWARDED_FOR'] );
    $_SERVER['REMOTE_ADDR'] = $http_x_headers[0];
}
```
Is that code secure enough?

**Comment by stodorovic** [comment]
It depends on the configuration. If there aren't way to anyone skip NGINX then it's fine. Maybe you need to set _$_SERVER['HTTPS']_ too because [is_ssl](https://developer.wordpress.org/reference/functions/is_ssl/) could return false (if NGINX locally use http protocol even if it's externally https).

One note, you forgot to add [trim](https://www.php.net/manual/en/function.trim.php) - `$_SERVER['REMOTE_ADDR'] = trim( $http_x_headers[0] );` (but it's rare case that there are more proxies in the chain).

**Comment by quantumleap33** [comment]
@stodorovic 

Ok, thanks!
