### ISSUE TITLE
Issue with Stripe Webhook

### ISSUE THREAD

**Issue by StrothiP** [Trumani/stop-spammers#146]
Hey guys,

I love the plugin as it significantly reduced the amount of spam on my system. Unfortunately I noticed recently that it is also blocking the webhook information being send by Stripe via Stripe Connect back to Memberpress, thus while the payment goes through, the information that the payment was successful is blocked by StopSpammers and thus then not processed.

If I switch on the "Only Use the Plugin for Standard WordPress Forms" option, it works indeed fine, but as I'm using other forms for registration than the standard WP forms, I then also end up with spam accounts :(

Is there any way to whitelist the webhook information from stripe? I can see that it's blocked in the backend, but I haven't found an option to whitelist it due to it being neither an email / ip?!

Any help would be highly appreciated!

Kind regards, Philip

**Comment by bhadaway** [comment]
Stripe is now cleared in the latest version.
