### ISSUE TITLE
recover my password

### ISSUE THREAD

**Issue by motor24** [Trumani/stop-spammers#149]
I did some tests and every time I want to recover my password I get this message. I tried several email addresses but the plugin behaves the same. I would like this message to appear to me only in the case of a spammer. Thanks.
![FireShot Capture 001 - Stop Spammers - motor24 ro](https://user-images.githubusercontent.com/60315618/73134844-173c4100-4044-11ea-86fb-b8b2fed66565.png)

**Comment by bhadaway** [comment]
This is obviously a very old issue now, but if anyone comes across this, please see:

https://github.com/bhadaway/stop-spammers/issues/5
