### ISSUE TITLE
2020.1 update is broken

### ISSUE THREAD

**Issue by breinmark** [Trumani/stop-spammers#152]
Encountered errors after updating the plugin to version 2020.1
wordpress site became completely inaccessible
error in firefox: “content decoding error”
error in safari: “cannot decode raw data”
could not access wp-admin anymore so using ftp had to rename the plugin to ***_old, which gave me access to wp-admin again
Then restored site from recent backup.

***NOTE:
in the plugin’s description I read:
“If you update to version 2020, please clear your cache to see the new UI.”
would that solve the problem? clearing the cache before updating?

similar problems are encountered by other users as well, see:
https://wordpress.org/support/topic/just-performed-update-and-getting-errors-all-over/
https://wordpress.org/support/topic/white-screen-of-death-203/
https://wordpress.org/support/plugin/stop-spammer-registrations-plugin/reviews/

**Comment by bhadaway** [comment]
This has been fixed.
