### ISSUE TITLE
Allow List Request

### ISSUE THREAD

**Issue by davidlav33** [Trumani/stop-spammers#153]
Hi,
Greetings !!

First of all I want to thank you for such a great plugin as it is helping a lot stopping the spams. I am new to stop spammer plugin and I am facing now an issue with receiving emails to allow list request. It says "A request has been received from someone who has been marked as a spammer by the Stop Spammers plugin." Is it possible to make it automatically removed or blocked or clear as I received a lot of spams ? Also there are lots of IP addresses in 'Personalized Allow List' section even when I never added any IP address to that section. Should I delete them or let it be like that ? Enable Allow by User Id in 'Personalized Allow List' is OFF.
It would be very helpful to me if you can please guide/help. 
Thank you,
Divakar

**Comment by bhadaway** [comment]
Hi Divakar,

1. Yes, if you go to: _Stop Spammers > Challenge & Deny_ you can turn off the option "Notify Webmaster When a User Requests to be Added to the Allow List."

2. IPs are generally whitelisted automatically when they're legitimate users, especially admins. If you've logged into your admin account from multiple locations, your house, your phone, from work, a friend's house, etc., it would whitelist all those IPs.

Thanks
