### ISSUE TITLE
Plugin Seems Not To Install

### ISSUE THREAD

**Issue by austincollinpena** [Trumani/stop-spammers#157]
Plugin is installed [on this site](https://stop-spammers.objectobject.io/index.php/stop-spam-test/) but doesn't seem to have initialized in any way. Feel free to try to trigger the contact form with what should be blocked. Happy to send WP credentials.

How should I debug this?

Notes:
- Added my IP to the block list
- Disabled "Enable Allow by User ID"
- Disabled "Automatically Add Admins to Allow List"

**Comment by bhadaway** [comment]
1. Are you able to use a VPN or proxy instead and then test blocking that IP?

2. Is your server detecting IPs correctly? This is vital, and special configuration is required if you're using a CDN like Cloudflare (https://support.cloudflare.com/hc/en-us/sections/200805497-Restoring-Visitor-IPs).

3. How was the form created? Is it a plugin (which plugin?), something implemented by the theme, or maybe a custom form you've added?

**Comment by austincollinpena** [comment]
> Are you able to use a VPN or proxy instead and then test blocking that IP?

Friend tried from overseas. Still couldn't trigger it.

> Is your server detecting IPs correctly? This is vital, and special configuration is required if you're using a CDN like Cloudflare

It is using Cloudflare for DNS, but not proxying traffic. It detected my IP no problem

> How was the form created?

Contact form 7 shortcode dropped onto a page.

**Comment by bhadaway** [comment]
Contact Form 7 uses a fairly straightforward form, so it should work.

Can you do a block test on the plain old registration form just to eliminate that possibility:

https://yoursite.com/wp-login.php?action=register

Make sure to double-check your friend's IP again (https://whatismyipaddress.com/ — and if it's an IPv6 address, that's definitely more complicated) right before he attempts to register.

Just to be sure, when you say it detected your IP correctly, are you referring to WordPress, Stop Spammers, or something else?
