### ISSUE TITLE
Elementor Form Builder: Spam Containing Links

### ISSUE THREAD

**Issue by jonathansoltero** [Trumani/stop-spammers#158]
Hello.

Form submission spam is passing through. Most bots are using Bit.ly links so can you add an option to block certain links like bit.ly?

Thank you.

**Comment by bhadaway** [comment]
This is a good idea.

A protection option to block common URL shortening services.

This looks like a pretty good list:

https://raw.githubusercontent.com/sambokai/ShortURL-Services-List/master/shorturl-services-list.txt

We'll definitely be considering this in a future update.

Thanks

**Comment by bhadaway** [comment]
Short URL blocking has now been added in Free and Elementor contact form protection has been added in Premium.
