### ISSUE TITLE
Cloudflare infrastructure changes

### ISSUE THREAD

**Issue by jonathanstegall** [Trumani/stop-spammers#169]
My host forwarded this message from Cloudflare:

> **[Action May Be Required] Changes to Cloudflare Infrastructure IPs Listed on cloudflare.com/IPs **
> 
> Cloudflare is making infrastructure changes to simplify customer configuration, and reduce the number of IPv4 addresses that could potentially interact with your origin on Cloudflare’s behalf. 
> 
> If your security model relies on allowing a list of trusted Cloudflare IPs from cloudflare.com/ips (http://www.cloudflare.com/ips) (or via API (https://api.cloudflare.com/#cloudflare-ips-properties)) on your origin, please make the following changes to your allow list by May 7, 2021. This change is safe to make today. 
> 
> Remove: 
> 104.16.0.0/12 
> 
> Add: 
> 104.16.0.0/13 
> 104.24.0.0/14 
> 
> This change delists the 104.28.0.0/14 prefix, which is no longer in use by Cloudflare infrastructure. These addresses will be repurposed for use with our Gateway and WARP (secure web gateway and VPN) products, and may carry traffic from untrusted sources in the future. 
> 
> Cloudflare does not recommend enforcing security policy at origins solely by trusting IP addresses. Argo Tunnels and Authenticated Origin Pulls provide more secure and specific ways to secure origin connections from Cloudflare.
> 
> * Further detail on how to configure Argo Tunnels. (https://developers.cloudflare.com/cloudflare-one/tutorials/multi-origin)
> * Further detail on how to configure Authenticated Origin Pulls. (https://developers.cloudflare.com/ssl/origin-configuration/authenticated-origin-pull)
> 
> If you have further questions, please visit the Cloudflare Community (https://community.cloudflare.com/).

I'm assuming the fix for this is what I'm seeing when I look at commit 50c3605faa2223e3c3ffa0d411e863d8f03fc268. Is that correct? If so, is there an ETA for when it will be released as a plugin update, or is it the kind of thing that folks should install manually?

**Comment by bhadaway** [comment]
It'll be in the next official update soon, but for a few reasons, we try not to submit updates too often:

1. This is actually against wporg policy. Posting too many updates can be seen as a sign of gaming/spamming the system, and even though this is never what we're doing, it's better to pace ourselves and avoid upsetting the admins.
2. It can be stressful for users to see too many updates happening at once, and they quite literally ask us what's wrong when we need to do too many rapid fire updates all at once.
3. I like to give some breathing room between updates to await further feedback and try and get other fixes in as well.
4. There's a certain development cycle we have and factors like: time, money, and resources play a part in it.
5. And finally, philosophically, I think it's important to just have breaks where things are stable and quiet for a while.
