### ISSUE TITLE
PHP 8 Issues? Report Those Here...

### ISSUE THREAD

**Issue by bhadaway** [Trumani/stop-spammers#171]
We're now upgrading Stop Spammers for PHP 8, so please, if the plugin is giving you any PHP errors, first verify that you're on version 8 by going to _Stop Spammers > Diagnostics > Show PHP_ Info and then if you are, comment below with the error(s).

**Comment by StrothiP** [comment]
Dear @bhadaway,

I just saw your request for errors. Please find the issue below:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function sfs_ErrorHandler(), 4 passed and exactly 5 expected in /var/www/web124/htdocs/FSLCI/wp-content/plugins/stop-spammer-registrations-plugin/includes/stop-spam-utils.php:101 Stack trace: #0 [internal function]: sfs_ErrorHandler(2, 'is_readable(): ...', '/var/www/web124...', 73) #1 /var/www/web124/htdocs/FSLCI/wp-includes/class-phpass.php(73): is_readable('/dev/urandom') #2 /var/www/web124/htdocs/FSLCI/wp-includes/class-phpass.php(221): PasswordHash->get_random_bytes(6) #3 /var/www/web124/htdocs/FSLCI/wp-includes/pluggable.php(2400): PasswordHash->HashPassword('hallo1234') #4 /var/www/web124/htdocs/FSLCI/wp-content/plugins/buddypress/bp-members/screens/register.php(226): wp_hash_password('hallo1234') #5 /var/www/web124/htdocs/FSLCI/wp-includes/class-wp-hook.php(303): bp_core_screen_signup('') #6 /var/www/web124/htdocs/FSLCI/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #7 /var/www/web124/htdocs/FSLCI/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #8 /var/www/web124/htdocs/FSLCI/wp-content/plugins/buddypress/bp-core/bp-core-dependency.php(388): do_action('bp_screens') #9 /var/www/web124/htdocs/FSLCI/wp-includes/class-wp-hook.php(303): bp_screens('') #10 /var/www/web124/htdocs/FSLCI/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #11 /var/www/web124/htdocs/FSLCI/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #12 /var/www/web124/htdocs/FSLCI/wp-content/plugins/buddypress/bp-core/bp-core-dependency.php(445): do_action('bp_template_red...') #13 /var/www/web124/htdocs/FSLCI/wp-includes/class-wp-hook.php(303): bp_template_redirect('') #14 /var/www/web124/htdocs/FSLCI/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #15 /var/www/web124/htdocs/FSLCI/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #16 /var/www/web124/htdocs/FSLCI/wp-includes/template-loader.php(13): do_action('template_redire...') #17 /var/www/web124/htdocs/FSLCI/wp-blog-header.php(19): require_once('/var/www/web124...') #18 /var/www/web124/htdocs/FSLCI/index.php(17): require('/var/www/web124...') #19 {main} thrown in /var/www/web124/htdocs/FSLCI/wp-content/plugins/stop-spammer-registrations-plugin/includes/stop-spam-utils.php on line 101 

Kind regards, Philip

**Comment by bhadaway** [comment]
> /wp-content/plugins/stop-spammer-registrations-plugin/includes/stop-spam-utils.php on line 101

Fixed.
