### ISSUE TITLE
Spam emails are getting in inbox

### ISSUE THREAD

**Issue by praharshgtplaza** [Trumani/stop-spammers#175]
I am getting spam emails on the email id on webixytechnologies@gmail.com from support@globaltradeplaza.com on every morning between 4:00AM to 5:00 PM.

I have installed the plugin on my WordPress dashboard and made updates as discussed on the website but still getting these spam emails. 

![WhatsApp Image 2022-09-01 at 11 59 41](https://user-images.githubusercontent.com/112609230/187849898-ee781f98-1cda-4d0a-a4bc-a8b4090d3de5.jpeg)

From the footer part of the image, you can find that it is pointing to our website  https://blogs.globaltradeplaza.com/  

Looking forward for best solutions to this error.

**Comment by bhadaway** [comment]
Unfortunately, Stop Spammers is not compatible with Contact Form 7, though if we're able to get funding (https://donorbox.org/stop-spammers), we'd love to add support for it.

I recommend my own Contact Form Zero, which has spam protections built-in, plus it's fully compatible with the protections of Stop Spammers:

https://wordpress.org/plugins/contact-form-zero/
