### ISSUE TITLE
Untitled mystery dashboard message

### ISSUE THREAD

**Issue by jrmain** [Trumani/stop-spammers#181]
I appreciate the work being done on this plugin, and I accept that using the free version involves seeing occasional promotional messages in the dashboard. However, it would be helpful if the dashboard messages identify the plugin involved. I've attached the latest, which doesn't mention StopSpammers at all.
![MysteryPopup](https://github.com/Trumani/stop-spammers/assets/1110694/d6229777-f3ea-485c-88fd-8732e93822e5)

**Comment by bhadaway** [comment]
We usually do, so just a small oversight. Thanks for the heads up!
