### ISSUE TITLE
Prevent allow list if email or ip matches in blacklist

### ISSUE THREAD

**Issue by siparker** [Trumani/stop-spammers#40]
I am having an issue where i have about 5 or 6 email addresses continually trying to signup.
They get blocked and then fill out the allow request form which sends me on average about 1300 emails a day.
If someone is in the blacklist i want them to be banned permanently with no ability to do anything. including the allow request.
I have to leave the allow request on as i often get real users trying to register who get blocked for one reason or another but all thats happening at the moment is my sendgrid credits are getting hammered and my deliverability rating is going through the floor..

**Comment by bhadaway** [comment]
Here are some different things you can try:

1. Keep the Allow Request form active, but just disable email notifications for them. Then, manually check the requests each day, and continue whitelisting real people and adding spammers to the blacklist until things hopefully calm down.

2. Disable the Allow Request form, but update the blocked message to inform legitimate users that they can email you at X if they're having issues registering or logging in. You'll all but eliminate the headache, and if it's only a few real people getting trapped in the filter here and there, hopefully it won't be too difficult to manually clear them.

3. Stop Spammers is only one line of defense. WordPress, your server, etc. can all be hardened in many other ways. You might consider setting up Cloudflare. You might consider hardening via .htaccess:

https://perishablepress.com/tag/blacklist/

**Comment by siparker** [comment]
Hi, Thanks for your reply,

I do have these steps in place. I turned off the notifications which obviously stopped them from coming through. 

I want to leave the allow request form on as i did get a few people most days who were trapped one way or another.

I have put in deny ip ranges to cover a lot of the issues with the spamming scripts but as you will know the IP just changes. in this case i had banned several C blocks from the ukraine but now there is a totally new set of IP's with the same set of emails trying to register 1300 times a day.

What i would really like to do is to get the deny list to flat out deny anyone and that is it. so any IP or email address that matches that list is never shown the allow list.

I dont know if there is any reason to allow that. If someone matches some other part of the stop spammer system and it is unsure on the spam level then sure i would like to have them see the allow list. but if someone is in an IP or using an email in the block list. I would rather redirect them to goatse straight away.

**Comment by bhadaway** [comment]
It's not a bad idea and I completely agree with your logic (so I've changed this from a question to an enhancement for possible future implementation), but I also want to help you solve your problem in the short-term.

Are you comfortable sharing your site publicly, more info about these particular spammers, and why your site is a desired target for them?

**Comment by siparker** [comment]
yeah,
its thetattooforum dot com 
I dont think i am being targeted for any other reason than its a mass spam campaign for essayurdite.com and my forum is about 10 years old so its on lists of domains to be targeted.

They fill out the allow list form with the proposed blog comment spam so no intelligence there.

Emails and Ip's
46.118.0.0/16
46.119.0.0/16
segnaw@outlook.com
yavmol@outlook.com
liprac@outlook.com
zofvak@outlook.com
retcav@outlook.com
kesvun@outlook.com
ficrop@outlook.com
xekcob@outlook.com

**Comment by bhadaway** [comment]
Okay, I have a creative solution I'd like you to try. I can see on your registration page that you use reCAPTCHA. I assume you signed up for this yourself so you could get the keys? If not, it's very simple.

Most likely that reCAPTCHA is set to the default settings, which makes it very easy on humans, and not the most difficult it can be for bots. Here's what I suggest:

1. From your WP admin main menu, go to: _Stop Spammers_ > _Challenge & Deny_.

2. Uncheck the box for "Allow Users to Add to the Allow Request List."

3. For "Second Chance CAPTCHA Challenge," select "Google ReCaptcha."

4. Go to https://www.google.com/recaptcha/admin and create a new _and_ separate key from your other one for your site. This time, increase the CAPTCHA difficulty/security settings to the highest that they'll go.

5. Paste in your new keys and save.

Trial it for at least 24 hours and let me know if the problem is greatly improved or even completely solved. That is, denied humans can still get in without much grief, and little to no bots are able to get through.

**Comment by siparker** [comment]
thats a really great idea. Done, I will report back on its success rate.

**Comment by siparker** [comment]
Hi, That worked very well. 4 allow requests instead of 400 over 24 hrs. very useful tip.

**Comment by bhadaway** [comment]
Happy to hear it.

Certainly, the plugin needs a lot of improvement, but there are enough options there for just about anyone to "baton down the hatches," I figured we should be able to come up with something.

Stop Spammers is definitely not a one-size-fits-all or out-of-the-box solution. I'm learning that its real usefulness is in the ability to custom refine things as needed on a case by case basis. Whatever works best for the specific site.
