### ISSUE TITLE
How to enable captcha even without the second chance triggered

### ISSUE THREAD

**Issue by zero-arc** [Trumani/stop-spammers#58]
Hi,
  Is there a feature or option that I can enable captcha on comment form, login form, registration form even if the second chance is not triggered? Cause I wanted to enable captcha even if the second chance is not triggered. I have been finding the options and still not found it. 
Please help...

**Comment by bhadaway** [comment]
That's actually a great question and idea. No, there's no option to have a CAPTCHA in place by default, but perhaps there should be.

In the meantime, I highly recommend using this plugin (in addition to Stop Spammers) to both improve the appearance, function, and security of registration and login forms:

https://wordpress.org/plugins/theme-my-login/

To add a CAPTCHA function only (including for comment forms), try this plugin instead:

https://wordpress.org/plugins/invisible-recaptcha/

**Comment by bhadaway** [comment]
This option has now been implemented in the free version of Stop Spammers.
