### ISSUE TITLE
Request: Export and Import Settings

### ISSUE THREAD

**Issue by bdwatt0** [Trumani/stop-spammers#67]
I manage a fair amount of sites for clients.  I plan on using your outstanding plugin for their Anti-Spam needs.  Any chance you could incorporate an Export and Import Settings option to make implementation easier for mass deployment?

Thanks for your hard work!

**Comment by bhadaway** [comment]
Good idea.

This should be fairly simple actually, and unless someone else contributes a solution in the meantime, I'll see if I can implement this in the near future.

Thanks

**Comment by bhadaway** [comment]
This feature is now available in Stop Spammers Premium.
